export const APP_ROUTES = {
  CRM_LOGIN: "login",
  SIGN_UP: "signup",
  CRM_HOME: "crm-home",
  CRM_WELCOME: "crm-welcome",
  MERCHANTS_INFO: "merchants_info",
  MERCHANT_DETAILS: "merchant-details",
  MERCHANT_SEARCH: "merchant-search",
  CREATE_MERCHANT: "create-merchant",
  CUSTOMER_DETAILS: "customer-details",
  ORDER_DETAILS: "order-details",
  CUSTOMER_SEARCH: "customer-search",
  MY_ACCOUNT: "my-account",
  CHANGE_PASSWORD: "change-password",
  VENDOR_GEO_MAPPING: "vendor-geo-mapping",
  VENDOR_GEO_DETAILS: "vendor-geo-details",
  PROMOTION_SEARCH: "promotion-search",
  DISTRIBUTOR_SEARCH: "distributor-search",
  CREATE_PROMOTION: "create-promotion",
  PROMOTION_DETAILS: "promotion-details",
  MERCHANT_Profile: "merchant-Profile",
}
